### ISSUE TITLE
时间轴

### ISSUE THREAD

**Issue by TonyBest318** [singularity-s0/frc6907-scouting-app#2]
### Bug

- 时间轴会走过终点走出画面
- 开始走动前，灰掉计次和放弃

### Feature

- 时间轴走动时，高亮当前时间片
- 走到终点时，点击时间片加载并编辑动作属性
- 当前时间无需两位毫秒显示，mm:ss即可
- 根据时间轴上当前时间片的开始时间，过滤右上角可以选择的动作阶段auto/tel/end

**Comment by singularity-s0** [comment]
给我一份 auto/tel/end 的时间段

**Comment by singularity-s0** [comment]
给我一份 auto/tel/end 的时间段
